### ISSUE TITLE
[data] Wilson's almost commuting basis

### ISSUE THREAD

**Issue by Antonio-JP** [Antonio-JP/dalgebra#40]
## **Theory**
As discussed in [doi:10.1145/3637529.3637531](https//www.doi.org/10.1145/3637529.3637531), given a generic differential polynomial of shape 
$$L_n = \partial^n  + u_{2}\partial^{n-2} + \ldots + u_{n-1}\partial + u_n,$$
there is a unique basis of almost commuting differential polynomials $P_m$ ($m \in \mathbb{N}$ and $P_{n,m}$ of order $m$). This result proved by Wilson, was extended computationally in the given reference.

## **Goal of the issue**
Implement a easy method to compute the Wilson's almost commuting polynomials $P_{n,m}$ for arbitrary $n$ and $m$.

## **Tasks**

* *Primary tasks*
- [x] Implement a method for computing the almost commuting basis for arbitrary values of $n$ and $m$.
- [x] Include pre-computed values in the repository to speed-up the use of the method.
- [x] Check compatiblity between versions of "Python" and "SageMath".
- [x] Allow reuse of the data between different versions of the package `dalgebra`

* *Optional tasks*
- [ ] Provide access to the data compatible with other Computer Algebra systems (such as Maple, Matlab, Mathematica, Julia, etc)
- [ ] Provide web access to this information.
